environment:
  matrix:
    - nodejs_version: "6.2.2"
    - nodejs_version: "6.3.0"
    - nodejs_version: "6.4.0"

skip_tags: true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off
test_script:
  - npm run builder:test

version: "{build}"
